services:
  nginx:
    image: nginx:alpine
    ports:
      - "8008:8008"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./web-4-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./web-4-backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/web4db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=web4db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 